# Generated by Django 4.2.16 on 2024-11-29 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_management', '0002_alter_education_table_alter_employee_table_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PreviousEmployee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_id', models.IntegerField()),
                ('name', models.CharField(max_length=100)),
                ('date_of_birth', models.DateField()),
                ('address', models.TextField()),
                ('position', models.CharField(max_length=50)),
                ('sex', models.CharField(max_length=10)),
                ('age', models.IntegerField()),
                ('deleted_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'PreviousEmployee',
            },
        ),
    ]
