# Generated by Django 4.2.16 on 2024-11-30 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_management', '0003_previousemployee'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='education',
            index=models.Index(fields=['degreecompleted'], name='Education_degreec_22883f_idx'),
        ),
        migrations.AddIndex(
            model_name='education',
            index=models.Index(fields=['major'], name='Education_major_bf4492_idx'),
        ),
        migrations.AddIndex(
            model_name='education',
            index=models.Index(fields=['gpa'], name='Education_gpa_661a7b_idx'),
        ),
        migrations.AddIndex(
            model_name='employee',
            index=models.Index(fields=['position'], name='Employee_positio_9a871b_idx'),
        ),
        migrations.AddIndex(
            model_name='employee',
            index=models.Index(fields=['sex'], name='Employee_sex_0608e2_idx'),
        ),
        migrations.AddIndex(
            model_name='office',
            index=models.Index(fields=['officeName'], name='Office_officeN_30f1e8_idx'),
        ),
        migrations.AddIndex(
            model_name='office',
            index=models.Index(fields=['establishedYear'], name='Office_establi_6ba2d0_idx'),
        ),
    ]
